# Hono IoT platform configuration
[hono]
# URL to the Hono HTTP adapter
http_adapter = "https://<your-hono-host>:<port>"
# Tenant identifier in Hono
tenant_id = "<your-tenant-id>"

[[devices]]
# The namespace where the device has permission to manage things
namespace = "internal"
# The Eclipse Ditto policy id to be used on the Ditto Protocol messages
policy_id = "meteo:default"
# The path to the client's authentication certificate
cert_path = "<path>"
# The path to the client's authentication private key
private_key = "<path>"

# The strategies that this device will use to acquire data and modify things.
# The strategies are developed in the strategies/ folder, and all follow a common structure.
# Currently implemented are the TrafficStrategy, the MeteoStrategy, the
# MeteoWarningsStrategy and the GeoJson Strategy.
# To use a given strategy, set its type and needed information in the
# `strategies` table of the device.
# A device can have any number of strategies as long as it has at least one strategy.
strategies = [{type="meteo", subject="meteo"}, {type="meteo_warnings", subject="meteo"}]
